version: "3"

services:
  app:
    image: us.gcr.io/serious-dialect-365703/assessment:1.0.0
    deploy:
      replicas: 2
    volumes:
      - .:/code
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:4000"
