version: "3"

services:
  app:
    build: .
    deploy:
      replicas: 2
    volumes:
      - .:/code
  nginx:
    image: nginx:latest
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:4000"